[package]
name = "git-grift"
version.workspace = true
edition.workspace = true

[dependencies]
clap = { workspace = true }
clap_complete = { workspace = true }
dirs = { workspace = true }
eyre = { workspace = true }
grift-core = { workspace = true }
