[package]
name = "grift-core"
version.workspace = true
edition.workspace = true

[dependencies]
eyre = { workspace = true }
git2 = { workspace = true }
octocrab = { workspace = true }
regex = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
